from typing import Protocol

from core.serializable_protocol import SerializableProtocol
from dto.application.application_dto import ApplicationDto


class ApplicationServiceProtocol(Protocol):
    def update_config(self, config: ApplicationDto) -> None: ...

    @property
    def system_count(self) -> int: ...

    @property
    def level_set_point(self) -> float: ...
    @level_set_point.setter
    def level_set_point(self, value: float) -> None: ...

    @property
    def level_offset(self) -> float: ...
    @level_offset.setter
    def level_offset(self, value: float) -> None: ...

    @property
    def start_pump_delay(self) -> int: ...
    @start_pump_delay.setter
    def start_pump_delay(self, value: int) -> None: ...

    @property
    def stop_pump_delay(self) -> int: ...
    @stop_pump_delay.setter
    def stop_pump_delay(self, value: int) -> None: ...

    @property
    def system_fail_to_start_delay(self) -> int: ...
    @system_fail_to_start_delay.setter
    def system_fail_to_start_delay(self, value: int) -> None: ...

    def to_serializable(self) -> SerializableProtocol: ...