from typing import Protocol, runtime_checkable

from device.base.device_protocol import DeviceProtocol
from dto.device.sensor_dto import SensorConfigDto


@runtime_checkable
class SensorProtocol(DeviceProtocol, Protocol):
    @property
    def value_scaled(self) -> float: ...

    @property
    def value_scaled_max(self) -> float: ...
    @value_scaled_max.setter
    def value_scaled_max(self, value: float) -> None: ...

    @property
    def value_scaled_min(self) -> float: ...
    @value_scaled_min.setter
    def value_scaled_min(self, value: float) -> None: ...

    @property
    def ai(self) -> int: ...

    @property
    def ai_max(self) -> int: ...
    @ai_max.setter
    def ai_max(self, value: int) -> None: ...

    @property
    def ai_min(self) -> int: ...
    @ai_min.setter
    def ai_min(self, value: int) -> None: ...

    @property
    def value_ma(self) -> float: ...

    @property
    def alarm_start_delay(self) -> float: ...
    @alarm_start_delay.setter
    def alarm_start_delay(self, value: float) -> None: ...

    @property
    def alarm_stop_delay(self) -> float: ...
    @alarm_stop_delay.setter
    def alarm_stop_delay(self, value: float) -> None: ...


    @property
    def alarm_start_high(self) -> float: ...
    @alarm_start_high.setter
    def alarm_start_high(self, value: float) -> None: ...

    @property
    def alarm_stop_high(self) -> float: ...
    @alarm_stop_high.setter
    def alarm_stop_high(self, value: float) -> None: ...

    @property
    def alarm_start_high_high(self) -> float: ...
    @alarm_start_high_high.setter
    def alarm_start_high_high(self, value: float) -> None: ...

    @property
    def alarm_stop_high_high(self) -> float: ...
    @alarm_stop_high_high.setter
    def alarm_stop_high_high(self, value: float) -> None: ...


    @property
    def alarm_start_low(self) -> float: ...
    @alarm_start_low.setter
    def alarm_start_low(self, value: float) -> None: ...

    @property
    def alarm_stop_low(self) -> float: ...
    @alarm_stop_low.setter
    def alarm_stop_low(self, value: float) -> None: ...

    @property
    def alarm_start_low_low(self) -> float: ...
    @alarm_start_low_low.setter
    def alarm_start_low_low(self, value: float) -> None: ...

    @property
    def alarm_stop_low_low(self) -> float: ...
    @alarm_stop_low_low.setter
    def alarm_stop_low_low(self, value: float) -> None: ...

    @property
    def config(self) -> SensorConfigDto: ...
    @config.setter
    def config(self, value: SensorConfigDto) -> None: ...