from typing import Protocol, Optional


class IOModuleProtocol(Protocol):
    def cleanup(self) -> None: ...

    def initialize(self) -> None: ...

    def is_managed_pos(self, io_pos: int) -> bool: ...

    @property
    def io_count(self) -> int: ...

    def get_value(self, pos: int) -> Optional[bool] | Optional[int]: ...

    def get_all_values(self) -> list[bool] | list[int]: ...
