from typing import Protocol


class IOModuleProtocol(Protocol):
    def cleanup(self) -> None: ...

    def initialize(self) -> None: ...

    def managed_pos(self, io_pos: int) -> bool: ...

    @property
    def io_count(self) -> int: ...