from typing import Protocol, runtime_checkable, Optional

from dto.device.sensor_dto import SensorConfigDto


@runtime_checkable
class DeviceServiceProtocol(Protocol):
    def get_device_total_run_time(self, device_name: str) -> float: ...

    def set_device_total_run_time(self, device_name: str, run_time: float) -> None: ...

    def add_device_total_run_time(self, device_name: str, run_time: float) -> float: ...

    def get_device_last_run_time(self, device_name: str) -> float: ...

    def set_device_last_run_time(self, device_name: str, run_time: float) -> None: ...

    def clear_device_run_times(self, device_name: str) -> None: ...

    def get_sensor_config(self, device_id: int, device_name: str, default: Optional[SensorConfigDto] = None) -> Optional[SensorConfigDto]: ...

    def set_sensor_config(self, device_name: str, sensor: SensorConfigDto) -> None: ...