from typing import Protocol

from core.serializable_protocol import SerializableProtocol


class IOServiceProtocol(Protocol):
    def get_digital_input_value(self, di_pos: int) -> bool: ...

    def get_digital_output_value(self, do_pos: int) -> bool: ...

    def set_digital_output_value(self, do_pos: int, value: bool) -> None: ...

    def get_analog_input_value(self, ai_pos: int) -> int: ...

    def get_analog_output_value(self, ai_pos: int) -> int: ...

    def set_analog_output_value(self, ai_pos: int, value: int) -> None: ...

    def scan(self) -> None: ...

    def to_serializable(self) -> SerializableProtocol: ...