from typing import Protocol

from device.base.device_protocol import DeviceProtocol
from device.base.device_status import EDeviceStatus


class DeviceRunnableProtocol(DeviceProtocol, Protocol):
    @property
    def status(self) -> EDeviceStatus: ...

    @property
    def can_run(self) -> bool: ...

    @property
    def can_run_auto(self) -> bool: ...

    @property
    def alarm_fail_to_start(self) -> bool: ...

    @property
    def run_time_current(self) -> float: ...

    @property
    def run_time_last(self) -> float: ...

    @property
    def run_time_total(self) -> float: ...

    @property
    def is_called_to_run(self) -> bool: ...

    def reset_run_time(self) -> None: ...

    def call_to_run(self) -> None: ...

    def stop(self) -> None: ...

    def set_emergency_stop(self, value: bool) -> None: ...