from typing import Protocol

from common.alarm.alarm_protocol import AlarmProtocol


class AnalogAlarmProtocol(AlarmProtocol, Protocol):
    def set_value(self, value: float) -> None: ...

    def set_start_delay(self, value: int) -> None: ...

    def get_start_delay(self) -> int: ...

    def set_stop_delay(self, value: int) -> None: ...

    def get_stop_delay(self) -> int: ...

    def set_start_high(self, value: float) -> None: ...

    def get_start_high(self) -> float: ...

    def set_start_high_high(self, value: float) -> None: ...

    def get_start_high_high(self) -> float: ...

    def set_stop_high(self, value: float) -> None: ...

    def get_stop_high(self) -> float: ...

    def set_stop_high_high(self, value: float) -> None: ...

    def get_stop_high_high(self) -> float: ...